-- MySQL Script generated by MySQL Workbench
-- sáb 20 mar 2021 19:08:05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pygenda
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pygenda
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pygenda` ;
USE `pygenda` ;

-- -----------------------------------------------------
-- Table `pygenda`.`agenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pygenda`.`agenda` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pygenda`.`telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pygenda`.`telefone` (
  `telefone` INT NOT NULL,
  `codigo` INT NOT NULL,
  PRIMARY KEY (`telefone`, `codigo`),
  INDEX `fk_table1_agenda_idx` (`codigo` ASC) VISIBLE,
  CONSTRAINT `fk_table1_agenda`
    FOREIGN KEY (`codigo`)
    REFERENCES `pygenda`.`agenda` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pygenda`.`email`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pygenda`.`email` (
  `email` VARCHAR(100) NOT NULL,
  `codigo` INT NOT NULL,
  PRIMARY KEY (`email`, `codigo`),
  INDEX `fk_email_agenda1_idx` (`codigo` ASC) VISIBLE,
  CONSTRAINT `fk_email_agenda1`
    FOREIGN KEY (`codigo`)
    REFERENCES `pygenda`.`agenda` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
